services:
  fileserv-app:
    image: fileserv-app
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./data:/app/data
      - ./etc:/app/etc

    restart: unless-stopped
